stages:
  - test
  - deploy

before_script:
  - uname -a
  - whoami 

test-php5.6:
  stage: test
  script:
    - phpunit -c phpunit.xml tests/

#test-php7:
#  stage: test
#  script: echo "Running tests with php7"
#
#other-test-campaign:
#  stage: test
#  script: echo "Dther test campaign"

deploy-staging:
  stage: deploy
  script: echo "Deploy on staging"
  environment: staging
  only:
    - develop

deploy-production:
  stage: deploy
  script:
    - ssh -t root@diego "cd /var/www/wwwsite && rm -r ListManager/ && git clone --recursive git@lamiral.mecaprotec.fr:serviceInfo/ListManager.git && chown www-data:www-data ListManager/ -R"
  environment: production
  when : manual
  only:
    - master
