#image: localhost:5000/listmanager_image

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

before_script:
  - uname -a
  - whoami
  - composer install

build-php5.6:
  stage: build
  script:
    - docker build -t localhost:5000/listmanager_image -f Dockerfile.jessie .
  tags:
    - shell

build-php7:
  stage: build
  script:
    - docker build -t localhost:5000/listmanager_image:stretch -f Dockerfile.stretch .
  tags:
    - shell

test-php5.6:
  image: localhost:5000/listmanager_image
  stage: test
  script:
    - composer install
    - phpunit --coverage-text --color=never -c phpunit.xml tests/
  tags:
    - docker

test-php7:
  image: localhost:5000/listmanager_image:stretch

  # autorisation des tests php7.0 à échouer, vu que php7.0 n'est pour le moment pas utilisé en production
  allow_failure: true
  stage: test
  script:
    - composer install
    - phpunit --coverage-text --color=never -c phpunit.xml tests/
  tags:
    - docker

pages:
  image: localhost:5000/listmanager_image
  tags:
    - docker
  stage: deploy
  script:
    - phpunit --coverage-html public --color=never -c phpunit.xml tests/
  artifacts:
    paths:
      - public
  only:
    - master

deploy-staging:
  stage: deploy
  script: echo "Deploy on staging"
  environment: staging
  only:
    - develop
  tags:
    - shell

deploy-production:
  stage: deploy
  script:
    - ssh -t root@diego "cd /var/www/wwwsite && rm -r ListManager/ && git clone --recursive git@lamiral.mecaprotec.fr:serviceInfo/ListManager.git && chown www-data:www-data ListManager/ -R"
  environment: production
  when : manual
  only:
    - master
  tags:
    - shell
