FROM debian:jessie

ENV http_proxy=http://scoudrais:achangertest@phil:8080/
ENV https_proxy=http://scoudrais:achangertest@phil:8080/


RUN apt update && apt install -y \
php5 \
php5-xdebug \
php5-sqlite \
wget \
git \
&& rm -rf /var/lib/apt/lists/*

RUN wget https://phar.phpunit.de/phpunit-5.7.phar
RUN chmod +x phpunit-5.7.phar
RUN mv phpunit-5.7.phar /usr/local/bin/phpunit
RUN wget https://getcomposer.org/composer.phar && chmod +x composer.phar
RUN mv composer.phar /bin/composer

WORKDIR /tmp
